// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjA0uJIqi7PTMUAyarrzh86roRqF2ColE',
    appId: '1:65733469730:web:31ff5498c0865b48468c7b',
    messagingSenderId: '65733469730',
    projectId: 'payflow-tiago',
    authDomain: 'payflow-tiago.firebaseapp.com',
    storageBucket: 'payflow-tiago.appspot.com',
    measurementId: 'G-Y3RR1TNP68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGtDKWisvJ2yrcjTy4yLTt7YY_-jTLwuI',
    appId: '1:65733469730:android:fffcdd7b9ac3fda3468c7b',
    messagingSenderId: '65733469730',
    projectId: 'payflow-tiago',
    storageBucket: 'payflow-tiago.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCVMJWVnT1_EbWlKfvlK4IFRD3CGJkyc',
    appId: '1:65733469730:ios:1c26da14ae11868c468c7b',
    messagingSenderId: '65733469730',
    projectId: 'payflow-tiago',
    storageBucket: 'payflow-tiago.appspot.com',
    androidClientId: '65733469730-531g3k2nhocnt2ojfii0vqpp653i7tnf.apps.googleusercontent.com',
    iosClientId: '65733469730-3sfvjcdpvg5te36iq5kp6so343fhrumu.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnCVMJWVnT1_EbWlKfvlK4IFRD3CGJkyc',
    appId: '1:65733469730:ios:1c26da14ae11868c468c7b',
    messagingSenderId: '65733469730',
    projectId: 'payflow-tiago',
    storageBucket: 'payflow-tiago.appspot.com',
    androidClientId: '65733469730-531g3k2nhocnt2ojfii0vqpp653i7tnf.apps.googleusercontent.com',
    iosClientId: '65733469730-3sfvjcdpvg5te36iq5kp6so343fhrumu.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
